### PR TITLE
fix crc-support run.sh script extra popd

### PR DESCRIPTION
**Pull request by lilyLuLiu**

### CODE REVIEW

**Comment by adrianriobo** [comment]
What is this extra popd doing in your case, I directly migrated this from qe-platform as it was there. Also just in case and to match all platforms this is still on the windows script https://github.com/crc-org/ci-definitions/blob/f67810d850e0a83b50da180bd3078425048ab453/crc-support/oci/lib/windows/run.ps1#L150

**Comment by lilyLuLiu** [comment]
@adrianriobo In windows script, there is a push(https://gitlab.cee.redhat.com/crc/qe-platform/-/blob/master/support/images/crc-support/oci/lib/windows/run.ps1?ref_type=heads#L126) that match the popd.

**Comment by adrianriobo** [comment]
Ahh I see but here there is too..I mean I think the wrong thing here is that on `unix/run.sh` the pushd is insde the if for download...and it should be outside (so it applies to download or install or both) no?

https://github.com/crc-org/ci-definitions/blob/main/crc-support/oci/lib/unix/run.sh#L94

I mean move that outside instead of remove the popd should work and then all platforms will match WDYT?

**Comment by adrianriobo** [comment]
:thinking:  what I was suggesting is to move the mkdir target and pushd target before the if (as we do on windows)

With the last change I think if we need to download and install is gonna fail cause is gonna download inside target and then popd and finally try to install from the previous folder not from target

**Comment by adrianriobo** [comment]
Kind of, `targetPath` value is not always `crc-support` i.e. if you wanna download a bundle typically the targetPath for it would be `~/OpenshiftLocal/bundle/4.17.6` as we want to keep it there

**Comment by lilyLuLiu** [comment]
@adrianriobo I get that we may need to download bundles in some scenarios. 
But the parameters `aBaseURL` & `aName` are the address for the download item, `aName` is the CRC installer name. The current logic does not support downloading the bundle.

**Comment by lilyLuLiu** [comment]
For the use of parameter `aName `, the functions `install crc` and `download bundle` can't be realized at the same time, right?

**Comment by adrianriobo** [comment]
yeah, may that was the thing confusing you, yeah in my pipeline i.e. I got the task download-bundle which is crc-support with some specific params and other task to donwload/ install crc with other set of parameters.

So yeah crc-support offer both modes but they can not be executed both at the same time

**Comment by lilyLuLiu** [comment]
Get it. Thanks for the detailed explanation. I have re-committed the code change.

**Review by adrianriobo — APPROVED** [review]
One last request, can you change the commit message to explain this fix matches the logic between platforms + includes the option to install crc binary directly on linux and add as prefix something like 
```bash
[crc-support] fix: "your message"
```

This will help us to later cherry-pick only commits for crc-support when creating a new version.

Otherwise LGTM

**Pull request merged**
